apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    app: rabbitmq
    project: roboshop
    tier: db
  ports:
  - protocol: TCP
    port: 5672 #service-port
    targetPort: 5672 #container-port